### ISSUE TITLE
Incorrect template rendering

### ISSUE THREAD

**Issue by phonkee** [rustache/rustache#129]
I have this template:

				templates.push("
					impl treasure::Model for {{ model }} {
						fn options() -> treasure::ModelOptions {
							return treasure::ModelOptions
							{
								name: \"{{model}}\",
							}
						}
					}
				".to_string());

The data for template is:

					let data = rustache::HashBuilder::new()
						.insert_string("model", "test");

Rendered template is:

 					impl treasure::Model for test 								name: "test",
							}
						}
					}

Which is incorrect.

**Comment by jruhland** [comment]
On first glance this looks like an issue with multiple curly braces being picked up as tags when they are in-fact not, stemming from compiler.rs
