### ISSUE TITLE
insert_vector/push_vector and insert_hash/push_hash should accept FnOnce, not Fn

### ISSUE THREAD

**Issue by netvl** [rustache/rustache#130]
Currently `HashBuilder::insert_{vector, hash}` and `VecBuilder::push_{vector, hash}` accept `Fn` for their function argument. This disallows moving out of the builder closure environment event though it is called only once in rustache code. Therefore, it is impossible, for example, to consume a vector of `String`s and use its contents directly - you always need to clone all of the strings. With `FnOnce` these extra allocations could be avoided.

**Comment by netvl** [comment]
BTW, this limitation is demonstrated in [this SO answer](http://stackoverflow.com/questions/32989440/how-can-i-convert-toml-rs-result-to-stdcollectionshashmap/32991066#32991066)

**Comment by jruhland** [comment]
I appreciate your effort on this, however I am personally not maintaining this project any longer, I'm happy to review/merge PRs.
