### ISSUE TITLE
Make render_text/render_file take a pointer

### ISSUE THREAD

**Issue by ilpianista** [rustache/rustache#145]
Please consider the following use case:

```
let data = HashBuilder::new();
for foo in &vec {
    let a = rustache::render_file(foo, data);
}
```

The above code will trigger `use of moved value: 'data'`.

Please could be possible to change the signature of render_file? This will obviously break other people code, but it's an easy build fix which opens to more use cases.

Thanks

**Comment by ilpianista** [comment]
My proposal goes against some [unofficial rust guidelines](https://aturon.github.io/features/functions-and-methods/input.html#let-the-client-decide-when-to-copy-and-where-to-place-data.-[fixme:-needs-rfc]) so maybe I'm doing it wrong?

**Comment by norru** [comment]
Same guidelines say it's not always the case https://aturon.github.io/features/functions-and-methods/input.html#minimizing-ownership-assumptions

I believe the former case is restricted to whether .clone() outside, or inside, the function body. If the first thing you're doing inside the function is to .clone() the parameter you getting then you may as well just let the client do it.

**Comment by norru** [comment]
By the way I am having a similar issue,

```
let data = HashBuilder::new();
for foo in &vec {
	data.insert_string(foo, something(foo))
}
```

The workaround for this is so cumbersome I won't bother posting. Hint: it requires a recursive auxiliary nested function.

**Comment by cardoe** [comment]
Try the following:
```
use rustache::{HashBuilder, Render};

let data = HashBuilder::new();
for foo in &vec {
    let a = foo.render(data);
}
```

**Comment by cardoe** [comment]
Please look at the proposed API in https://github.com/cardoe/rustache/blob/9748a678fe8815d8e9373a5085d53846d06b5326/README.md and let me know if that would make things easier for you?

**Comment by ilpianista** [comment]
Yes, it does!
