### ISSUE TITLE
bump 0.0.4 or 0.1.0

### ISSUE THREAD

**Issue by cardoe** [rustache/rustache#147]
Since `memstream` is no longer a dependency can we bump the version?

**Comment by cardoe** [comment]
@jruhland I'll gladly do releases for this project if you run `cargo owner -a cardoe` in your checkout of rustache.

**Comment by jruhland** [comment]
you got it

**Comment by jruhland** [comment]
Done, sorry I have a lot of stuff going on, and sometimes i read the requests here and forget to do them :(

```shell
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Owner adding ["cardoe"] to crate rustache
```

**Comment by cardoe** [comment]
No worries. We all get busy and drift in and out of projects. I've got a handful of requests for some other projects that I need to get to but just don't have the time. Thanks for giving me access.

**Comment by cardoe** [comment]
Bumped to 0.0.4.
