### ISSUE TITLE
"rv" should be "out" in the first example

### ISSUE THREAD

**Issue by ayourtch** [rustache/rustache#159]
Just a typo I spotted:

the last line in the first example reads:

`println!("{}", String::from_utf8(rv.into_inner()).unwrap());
`

It should be:

`println!("{}", String::from_utf8(out.into_inner()).unwrap());
`

**Comment by cardoe** [comment]
Thanks for the fix. I'd however, recommend looking at https://crates.io/crates/mustache as it has a cleaner API and I switched to using that.
